allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
patchedDependencies:
  '@analogjs/router@2.7.1': patches/@analogjs__router@2.7.1.patch
